2025-03-11 10:57:17 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 10:57:17 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 13:13:27 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 13:13:27 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 13:13:36 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 13:13:36 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 13:13:40 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 13:13:40 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 13:16:44 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 13:16:44 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 14:08:29 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 14:08:29 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 14:19:53 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 14:19:53 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 14:19:54 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 14:19:54 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 14:29:15 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 14:29:15 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 14:29:15 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 14:29:15 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 14:29:19 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 14:29:19 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 14:29:20 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 14:29:20 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 16:03:09 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 16:03:09 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 16:03:10 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 16:03:10 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 16:03:24 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 16:03:24 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 16:03:25 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 16:03:25 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 16:07:24 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 16:07:24 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 16:07:24 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 16:07:24 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 16:16:54 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 16:16:54 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 16:16:55 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 16:16:55 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 16:17:26 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 16:17:26 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 16:17:27 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 16:17:27 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 16:19:09 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 16:19:09 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 16:19:10 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 16:19:10 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 16:20:23 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 16:20:23 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 16:20:23 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 16:20:23 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 16:23:54 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 16:23:54 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 16:23:55 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 16:23:55 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 16:45:30 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 16:45:30 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 16:45:30 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 16:45:30 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 16:46:55 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 16:46:55 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 16:46:56 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 16:46:56 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 16:48:20 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 16:48:20 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 16:48:21 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 16:48:21 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 16:52:53 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 16:52:53 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 16:52:54 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 16:52:54 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 16:53:07 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 16:53:07 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 16:53:07 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 16:53:07 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 16:53:10 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 16:53:10 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 16:53:10 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 16:53:10 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 16:56:29 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 16:56:29 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 16:56:30 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 16:56:30 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 16:56:33 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 16:56:33 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 16:56:34 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 16:56:34 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 16:59:31 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 16:59:31 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 16:59:31 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 16:59:31 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 16:59:36 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 16:59:36 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 16:59:36 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 16:59:36 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 17:00:03 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 17:00:03 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 17:00:03 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 17:00:03 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 17:00:08 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 17:00:08 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 17:00:09 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 17:00:09 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 17:00:22 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 17:00:22 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 17:00:23 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 17:00:23 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 17:30:46 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 17:30:46 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 17:32:03 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 17:32:03 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 17:34:16 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 17:34:16 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 17:36:24 - my_app - [31mERROR[0m - service_standart_router.py:192 - [31mcreate_service_standart_route: Системная ошибка при создании сервиса: StandardServiceService.update_standart_service() got an unexpected keyword argument 'name'[0m
Traceback (most recent call last):
  File "/home/gob/PycharmProjects/manicure/app/api/v1/services/service_standart_router.py", line 145, in update_service_standart_route
    service = await StandardServiceService.update_standart_service(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: StandardServiceService.update_standart_service() got an unexpected keyword argument 'name'
2025-03-11 17:41:07 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 17:41:07 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 17:44:59 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 17:44:59 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 17:45:36 - my_app - [31mERROR[0m - service_standart_router.py:194 - [31mcreate_service_standart_route: Системная ошибка при создании сервиса: Unknown filter param 'service_id'. Allowed base values are ['created_at', 'file_name', 'file_path', 'height', 'id', 'is_main', 'large', 'medium', 'mime_type', 'original', 'size', 'small', 'sort_order', 'standard_service', 'standard_service_id', 'updated_at', 'width'][0m
Traceback (most recent call last):
  File "/home/gob/PycharmProjects/manicure/app/api/v1/services/service_standart_router.py", line 155, in update_service_standart_route
    old_photo = await PhotoHandler.get_photo_by_id(model=StandardServicePhoto, service_id=service_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gob/PycharmProjects/manicure/app/use_case/photo_service/photo_base_servise.py", line 250, in get_photo_by_id
    return await PhotoRepository.get_photo(model, **filters)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gob/PycharmProjects/manicure/app/db/repositories/photo_repositories/photo_repository.py", line 139, in get_photo
    return await model.filter(**filters).first()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gob/.cache/pypoetry/virtualenvs/manicure-sVwaCYdo-py3.12/lib/python3.12/site-packages/tortoise/queryset.py", line 1051, in __await__
    self._make_query()
  File "/home/gob/.cache/pypoetry/virtualenvs/manicure-sVwaCYdo-py3.12/lib/python3.12/site-packages/tortoise/queryset.py", line 1013, in _make_query
    self.resolve_filters(
  File "/home/gob/.cache/pypoetry/virtualenvs/manicure-sVwaCYdo-py3.12/lib/python3.12/site-packages/tortoise/queryset.py", line 142, in resolve_filters
    modifier &= node.resolve(model, model._meta.basetable)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gob/.cache/pypoetry/virtualenvs/manicure-sVwaCYdo-py3.12/lib/python3.12/site-packages/tortoise/expressions.py", line 369, in resolve
    return self._resolve_kwargs(model, table)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gob/.cache/pypoetry/virtualenvs/manicure-sVwaCYdo-py3.12/lib/python3.12/site-packages/tortoise/expressions.py", line 327, in _resolve_kwargs
    key, value = self._get_actual_filter_params(model, raw_key, raw_value)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gob/.cache/pypoetry/virtualenvs/manicure-sVwaCYdo-py3.12/lib/python3.12/site-packages/tortoise/expressions.py", line 321, in _get_actual_filter_params
    raise FieldError(f"Unknown filter param '{key}'. Allowed base values are {allowed}")
tortoise.exceptions.FieldError: Unknown filter param 'service_id'. Allowed base values are ['created_at', 'file_name', 'file_path', 'height', 'id', 'is_main', 'large', 'medium', 'mime_type', 'original', 'size', 'small', 'sort_order', 'standard_service', 'standard_service_id', 'updated_at', 'width']
2025-03-11 17:48:04 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 17:48:04 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 17:49:52 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 17:49:52 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 17:50:11 - my_app - [31mERROR[0m - photo_base_servise.py:218 - [31mОшибка при удалении фото (ID: <StandardServicePhoto>): int() argument must be a string, a bytes-like object or a real number, not 'StandardServicePhoto'[0m
2025-03-11 17:50:11 - my_app - [31mERROR[0m - service_standart_router.py:195 - [31mcreate_service_standart_route: Системная ошибка при создании сервиса: 500: Ошибка при удалении фото[0m
Traceback (most recent call last):
  File "/home/gob/PycharmProjects/manicure/app/use_case/photo_service/photo_base_servise.py", line 201, in delete_photo
    photo = await PhotoRepository.get_photo_by_id(model,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gob/PycharmProjects/manicure/app/db/repositories/photo_repositories/photo_repository.py", line 39, in get_photo_by_id
    return await model.filter(id=photo_id).first()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gob/.cache/pypoetry/virtualenvs/manicure-sVwaCYdo-py3.12/lib/python3.12/site-packages/tortoise/queryset.py", line 1051, in __await__
    self._make_query()
  File "/home/gob/.cache/pypoetry/virtualenvs/manicure-sVwaCYdo-py3.12/lib/python3.12/site-packages/tortoise/queryset.py", line 1013, in _make_query
    self.resolve_filters(
  File "/home/gob/.cache/pypoetry/virtualenvs/manicure-sVwaCYdo-py3.12/lib/python3.12/site-packages/tortoise/queryset.py", line 142, in resolve_filters
    modifier &= node.resolve(model, model._meta.basetable)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gob/.cache/pypoetry/virtualenvs/manicure-sVwaCYdo-py3.12/lib/python3.12/site-packages/tortoise/expressions.py", line 369, in resolve
    return self._resolve_kwargs(model, table)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gob/.cache/pypoetry/virtualenvs/manicure-sVwaCYdo-py3.12/lib/python3.12/site-packages/tortoise/expressions.py", line 331, in _resolve_kwargs
    filter_modifier = self._resolve_regular_kwarg(model, key, value, table)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gob/.cache/pypoetry/virtualenvs/manicure-sVwaCYdo-py3.12/lib/python3.12/site-packages/tortoise/expressions.py", line 290, in _resolve_regular_kwarg
    criterion, join = self._process_filter_kwarg(model, key, value, table)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gob/.cache/pypoetry/virtualenvs/manicure-sVwaCYdo-py3.12/lib/python3.12/site-packages/tortoise/expressions.py", line 275, in _process_filter_kwarg
    else model._meta.db.executor_class._field_to_db(field_object, value, model)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gob/.cache/pypoetry/virtualenvs/manicure-sVwaCYdo-py3.12/lib/python3.12/site-packages/tortoise/backends/base/executor.py", line 178, in _field_to_db
    return field_object.to_db_value(attr, instance)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gob/.cache/pypoetry/virtualenvs/manicure-sVwaCYdo-py3.12/lib/python3.12/site-packages/tortoise/fields/base.py", line 260, in to_db_value
    value = self.field_type(value)  # pylint: disable=E1102
            ^^^^^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'StandardServicePhoto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gob/PycharmProjects/manicure/app/api/v1/services/service_standart_router.py", line 159, in update_service_standart_route
    await PhotoHandler.delete_photo(model=StandardServicePhoto, photo_id=old_photo)
  File "/home/gob/PycharmProjects/manicure/app/use_case/photo_service/photo_base_servise.py", line 219, in delete_photo
    raise HTTPException(status_code=500, detail="Ошибка при удалении фото")
fastapi.exceptions.HTTPException: 500: Ошибка при удалении фото
2025-03-11 17:54:37 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 17:54:37 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 17:57:50 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 17:57:50 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 18:00:03 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 18:00:03 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 18:23:35 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 18:23:35 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 18:26:08 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 18:26:08 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 18:30:33 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 18:30:33 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 18:39:55 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 18:39:55 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 18:41:01 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 18:41:01 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 18:47:57 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 18:47:57 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 18:55:54 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 18:55:54 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 19:04:37 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 19:04:37 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 19:11:24 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 19:11:24 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 19:14:54 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 19:14:54 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
2025-03-11 19:16:22 - my_app - [31mERROR[0m - service_standart_router.py:228 - [31mСистемная ошибка при удалении страндартной услуги: 'StandardService' object has no attribute 'user_id'[0m
2025-03-11 19:18:57 - my_app - [31mERROR[0m - logging_config.py:79 - [31mError message[0m
2025-03-11 19:18:57 - my_app - [31m[1mCRITICAL[0m - logging_config.py:80 - [31m[1mCritical message[0m
